FROM node:22.12.0

WORKDIR /nest-app

COPY package.json .

COPY *.lock .

RUN npm config set registry https://registry.npmmirror.com/

RUN npm install -g pnpm

RUN pnpm install

COPY . .

RUN pnpm run build 

EXPOSE 9527

CMD ["node", "./dist/main.js"]
